name: Auto Generate README

on:
  push:
    branches:
      - main  # Specify the branch you want to trigger on

jobs:
  generate_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Read content from file
      id: read_file
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const response = await github.repos.getContent({
            owner: 'appsaeed',
            repo: 'appsaeed',
            path: 'README.md', // Specify the path to your README.md file
          });
          const content = Buffer.from(response.data.content, 'base64').toString();
          console.log(content);
          return content; // Return content directly without wrapping in an object
    
    - name: Generate README
      run: |
        echo "# My Project" > README.md
        echo "${{ steps.read_file.outputs.result }}" >> README.md
        echo "Last updated: $(date)" >> README.md
        
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Automatically generated README"
        branch: ${{ github.ref }}
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"
        repository: ${{ github.repository }}
