name: Deploy local project to Github Pages
on:
  push:
    branches:
      - main
  workflow_dispatch: null
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Saeed Set up Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - name: Saeed Install node_modules
      run: npm install
    - name: Saeed Build Page
      run: npm run build
    - name: Saeed Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: Saeed production-files
        path: ./dist
  deploy:
    name: Saeed Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Saeed Download artifact
        uses: actions/download-artifact@v2
        with:
          name: Saeed production-files
          path: ./dist
      - name: Saeed Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
